@startuml

package twisk.exceptions{
    class ArcException{
    }
    class MondeException{
    }
    class TimeException{
    }
    class TwiskException{
    }
    class FileException{
    }
}

@enduml